package com.github.jershell.shadcn.metalbutton

import com.github.jershell.shadcn.components.metalbutton.*
import kotlin.math.abs
import kotlin.test.*

class MetalMathTest {
    private data class Sample(val preset: MetalPreset, val dark: Boolean, val u: Double, val v: Double,
        val time: Double, val r: Double, val g: Double, val b: Double)

    @Test fun plasmaMatchesIndependentSourceShaderReferenceSamples() {
        // Generated by imports/metal-fx/reference-samples.mjs from pinned source presets/GLSL.
        val samples = listOf(
            Sample(MetalPreset.Chromatic, true, 0.5, 0.5, 0.0, 0.5913251783344967, 0.6670678726456003, 0.5357213223431326),
            Sample(MetalPreset.Chromatic, true, 0.1, 0.9, 2.5, 0.0026845562048764047, 0.0040218240009816265, 0.004547673397919306),
            Sample(MetalPreset.Chromatic, true, 0.82, 0.31, 11.0, 0.051096278425378, 0.07652749374581834, 0.0863524001060866),
            Sample(MetalPreset.Chromatic, false, 0.5, 0.5, 0.0, 0.8647065914751505, 0.8586000592933956, 0.8586000592933956),
            Sample(MetalPreset.Chromatic, false, 0.1, 0.9, 2.5, 0.9544838291327078, 0.6142889940049436, 0.6142889940049436),
            Sample(MetalPreset.Chromatic, false, 0.82, 0.31, 11.0, 0.9619163495453816, 0.9619163495453816, 0.9619163495453816),
            Sample(MetalPreset.Silver, true, 0.5, 0.5, 0.0, 0.3415657241430256, 0.3387787627554823, 0.33599708221094526),
            Sample(MetalPreset.Silver, true, 0.1, 0.9, 2.5, 0.7073400990596471, 0.707148368325965, 0.7069566495879295),
            Sample(MetalPreset.Silver, true, 0.82, 0.31, 11.0, 0.0038042485995928963, 0.0038042483258429256, 0.0038042480520929594),
            Sample(MetalPreset.Silver, false, 0.5, 0.5, 0.0, 0.9013851576515561, 0.9013851576515561, 0.9013851576515561),
            Sample(MetalPreset.Silver, false, 0.1, 0.9, 2.5, 0.9065104530079068, 0.9065104530079068, 0.9065104530079068),
            Sample(MetalPreset.Silver, false, 0.82, 0.31, 11.0, 0.9061474812863667, 0.9061474812863667, 0.9061474812863667),
            Sample(MetalPreset.Gold, true, 0.5, 0.5, 0.0, 0.590831377237323, 0.5883948990315633, 0.58311227685906),
            Sample(MetalPreset.Gold, true, 0.1, 0.9, 2.5, 0.025420990702288714, 0.024213198051990202, 0.021638414795174494),
            Sample(MetalPreset.Gold, true, 0.82, 0.31, 11.0, 0.02554233189058959, 0.024319961969012486, 0.021714472176978458),
            Sample(MetalPreset.Gold, false, 0.5, 0.5, 0.0, 0.911927236177218, 0.8894237983301503, 0.801431485341379),
            Sample(MetalPreset.Gold, false, 0.1, 0.9, 2.5, 0.9433423349541282, 0.9009874084846172, 0.754728776490381),
            Sample(MetalPreset.Gold, false, 0.82, 0.31, 11.0, 0.9477727376662889, 0.9143489916710257, 0.8053675476633777),
        )
        samples.forEach { sample ->
            val actual = sampleMetal(sample.u, sample.v, sample.time, metalMode(sample.preset, sample.dark))
            assertEquals(sample.r, actual.r, 0.000001, sample.toString())
            assertEquals(sample.g, actual.g, 0.000001, sample.toString())
            assertEquals(sample.b, actual.b, 0.000001, sample.toString())
        }
    }

    @Test fun perimeterClosesAndStaysInsideTheSpecifiedSilhouette() {
        for (variant in MetalVariant.entries) {
            val geometry = MetalGeometry(if (variant == MetalVariant.Button) 140f else 40f,
                40f, 20f, variant, 1f, 1.6f)
            assertEquals(geometry.point(0f), geometry.point(geometry.perimeter))
            repeat(200) { index ->
                val point = geometry.point(index / 200f * geometry.perimeter)
                assertTrue(point.x >= -0.001f && point.x <= geometry.width + 0.001f)
                assertTrue(point.y >= -0.001f && point.y <= geometry.height + 0.001f)
            }
        }
    }

    @Test fun ringSamplingIsBoundedAndProducesFiniteNormalizedColors() {
        val mode = metalMode(MetalPreset.Chromatic, true)
        val geometry = MetalGeometry(1000f, 200f, 100f, MetalVariant.Button, 1f, 1.6f)
        val frame = createMetalFrame(geometry, 2.5, mode, 2f)
        assertEquals(513, frame.ring.size)
        assertEquals(16, frame.perimeterColors.size)
        frame.ring.forEach {
            assertTrue(it.color.r.isFinite() && it.color.r in 0.0..1.0)
            assertTrue(it.color.g.isFinite() && it.color.g in 0.0..1.0)
            assertTrue(it.color.b.isFinite() && it.color.b in 0.0..1.0)
        }
    }

    @Test fun glowHonorsDwellBeforeMovingToBrighterPerimeterPoint() {
        val geometry = MetalGeometry(140f, 40f, 20f, MetalVariant.Button, 1f, 1.6f)
        val state = MetalGlowState()
        fun frame(bright: Int) = MetalFrame(emptyList(), List(16) {
            if (it == bright) MetalRgb(1.0, 1.0, 1.0) else MetalRgb(0.0, 0.0, 0.0)
        })
        val initial = state.update(geometry, frame(0), 0.0, true)
        val held = state.update(geometry, frame(8), 2.0, true)
        assertEquals(initial.center, held.center)
        state.update(geometry, frame(8), 4.0, true)
        val relocated = state.update(geometry, frame(8), 6.0, true)
        assertNotEquals(initial.center, relocated.center)
        assertTrue(relocated.opacity in 0f..1f)
    }
}
